### ISSUE TITLE
Update with config options

### ISSUE THREAD

**Issue by flukejones** [zarathir/lapce-dart#1]
Proabably need something like this now:

```toml
name = "lapce-dart"
version = "0.0.1"
author = "zarathir"
display-name = "Dart"
description = "Dart for Lapce: powered by dart language-server"
wasm = "bin/lapce-dart.wasm"

[activation]
language = ["dart"]

[config."serverPath"]
default = "/home/luke/Android/flutter/bin/dart"
description = "Path to dart executable"

[config."serverArgs"]
default = "language-server --client-id zarathir.lapce-dart --client-version 1.2"
description = "Args for dart lsp"
```

this is what works for me, the defaults are just copy/paste from what I set in lapce settings. Although the actual aerverArgs I set looks like `"language-server", "--client-id zarathir.lapce-dart", "--client-version 1.2"`
